paketo-buildpacks/samples

java/native-image/pom.xml

Future versions of the buildpack will no longer contribute this dependency if it is missing.
Signed-off-by: Emily Casey <ecasey@vmware.com>

Include spring-graalvm-native dependency in pom.xml.

---

README.md
go/no-imports/README.md
go/no-imports/main.go
tests/go_test.go

- Adds a sample that does not import any modules to demonstrate that
workflow which is supported by the Go buildpack
- Adds this sample to the tests
Resolves #12

Adds sample Go app that does not import modules

---

java/native-image/java-native-image-sample/README.md
java/native-image/java-native-image-sample/pom.xml
java/native-image/java_native_image_test.go

* BP_BOOT_NATIVE_IMAGE has been deprecated in favor of BP_NATIVE_IMAGE
* Paketo Spring Boot Native Image renamed to Paketo Native Image Buildpack
* Adds maven plugin usage to native image samples
This won't pass until https://github.com/paketo-buildpacks/full-builder/pull/176 merges, but https://github.com/paketo-buildpacks/full-builder/pull/176 can't merge until samples pass

Updates for new native-image usage

---

.github/workflows/java-application-insights.yml
.github/workflows/java-aspectj.yml
.github/workflows/java-maven.yml
.github/workflows/java-native-image.yml
.github/workflows/java-war.yml
java/application-insights/pom.xml
java/aspectj/pom.xml
java/maven/pom.xml
java/native-image/java-native-image-sample/pom.xml
java/war/pom.xml

Use Java 11 instead of Java 8
It's still valid to use Java 8, but it is towards the end of its lifecycle. Java 11 has been out a while, is stable and it should be what most stable apps are using now.
This will still result in unit tests being run against both Java 8 & Java 11. It will shift to using Java 11 when running the integration tests.

Bump to use Java 11

---

php/httpd/README.md
php/php_test.go

It is httpd here instead of nginx
Correcting the readme of a sample

Correct header

---

ca-certificates/README.md

We don't need these flags as the `ca-certificates` buildpack is included in the `go` buildpack order.

Removes extraneous references to ca-certificates buildpack

---

python/poetry-run/poetry.lock
python/poetry-run/pyproject.toml
python/poetry/poetry.lock
python/poetry/pyproject.toml

The recent introduction of python 3.10 broke the poetry sample applications. The best way to fix this is to update the dependencies to versions that support 3.10 and greater.
We also removed some unnecessary transitive dependencies from the dependency list, as `poetry` does a better job at identifying transitive dependencies than other package managers.
Closes #271 #270

Use latest dependencies for poetry apps.

---

.github/workflows/test-all-samples.yml

instead of a different label for each language family
`gh issue create --label <label-name>` fails if the label doesn't already exist on the repo (as seen [here](https://github.com/paketo-buildpacks/samples/runs/6198576064?check_suite_focus=true#step:5:16)). So I've added a `test-failure` label to this repo.
This PR makes all test failures generate labels with a `test-failure` label, instead of a label prefixed with the language family name.

Use one test-failure label

---

.github/workflows/test-all-samples.yml

To more easily describe failures for multiple test suites on the same issue.
Updated title and body will look like:
[Test some-language-family workflow](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}) failed. Please take a look to ensure samples are working. (cc @paketo-buildpacks/content-maintainers)"
Another failure occurred: [Test other-language workflow](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}) failed.

Tweak test failure issue title and body contents

---

python/pipenv/Pipfile
python/pipenv/Pipfile.lock

This PR fixes the Pipenv smoke tests to work with newer versions of Pipenv.
Newer versions of Pipenv do not accept this partially-formed `[[source]]` directive in the `Pipfile`. As part of this we also have to regenerate the `Pipfile.lock` to be consistent with the updated `Pipfile`.
Resolves #431

Update python pipenv smoke tests.

---

.github/workflows/java-akka.yml
.github/workflows/java-application-insights.yml
.github/workflows/java-aspectj.yml
.github/workflows/java-dist-zip.yml
.github/workflows/java-gradle.yml
.github/workflows/java-kotlin.yml
.github/workflows/java-leiningen.yml
.github/workflows/java-maven.yml
.github/workflows/java-native-image.yml
.github/workflows/java-opentelemetry.yml
.github/workflows/java-war.yml
.github/workflows/test-all-samples.yml
.github/workflows/test-pull-request-ca-certificates.yml
.github/workflows/test-pull-request-dotnet-core.yml
.github/workflows/test-pull-request-git.yml
.github/workflows/test-pull-request-go.yml
.github/workflows/test-pull-request-java-native-image.yml
.github/workflows/test-pull-request-java.yml
.github/workflows/test-pull-request-nodejs.yml
.github/workflows/test-pull-request-php.yml
.github/workflows/test-pull-request-procfile.yml
.github/workflows/test-pull-request-python.yml
.github/workflows/test-pull-request-ruby.yml
.github/workflows/test-pull-request-web-servers.yml

This PR adds merge_group as a trigger in preparation for enabling Github Merge Queues.
Enable Github Merge Queues.

Add merge_group as a trigger

---

php/app_with_extensions/README.md
php/builtin-server/README.md
php/composer/README.md
php/composer_with_extensions/README.md
php/httpd/README.md
php/memcached_session_handler/README.md
php/nginx/README.md
php/redis_session_handler/README.md

PHP is the rare case that doesn't run on any stack other than Full. It's easy for new users to overlook this!

php apps: explicitly ask for full builder

---

.github/workflows/test-all-samples.yml
.github/workflows/test-pull-request-ca-certificates.yml
.github/workflows/test-pull-request-dotnet-core.yml
.github/workflows/test-pull-request-git.yml
.github/workflows/test-pull-request-go.yml
.github/workflows/test-pull-request-java-native-image.yml
.github/workflows/test-pull-request-java-node.yml
.github/workflows/test-pull-request-java.yml
.github/workflows/test-pull-request-nodejs.yml
.github/workflows/test-pull-request-php.yml
.github/workflows/test-pull-request-procfile.yml
.github/workflows/test-pull-request-python.yml
.github/workflows/test-pull-request-ruby.yml
.github/workflows/test-pull-request-web-servers.yml
README.md
ca-certificates/ca-certificates-sample/README.md
ca-certificates/ca-certificates-sample/buildpack/buildpack.toml
ca-certificates/ca-certificates_test.go
scripts/.util/test-workflow-template.yml
scripts/smoke.sh
web-servers/httpd-sample/README.md
web-servers/httpd-sample/httpd.conf
web-servers/no-config-file-sample/HTTPD.md
web-servers/no-config-file-sample/NGINX.md

Remove all bionic builder uses.
Replace with jammy builder wherever jammy builders weren't used.
Also for httpd tests: modify test app to work on jammy stack
Fixes #624

Update builders from bionic -> jammy

---

.github/workflows/java-gradle.yml
java/gradle/README.md
java/gradle/bindings/gradle-wrapper/gradle-wrapper.properties
java/gradle/bindings/gradle-wrapper/type
java/gradle/gradle/wrapper/gradle-wrapper.properties
java/gradle/smoke_test/gradle_test.go

Add documentation for gradle-wrapper.properties binding

---

.github/workflows/java-gradle.yml
java/gradle/gradle/wrapper/gradle-wrapper.properties

This PR changes `networkTimeout=1` to `networkTimeout=10000` in the gradle sample [gradle-wrapper.properties](https://github.com/paketo-buildpacks/samples/blob/main/java/gradle/gradle/wrapper/gradle-wrapper.properties) file and then changes the Action to use that properties file instead of copying a different file.
This fixes #642.
We're building our buildpacks in a CI/CD Jenkins pipeline and pushing them to our internal AWS ECR. We're using the samples to test our builds and this sample recently started to fail. I would expect the sample to run out-of-the-box. I'm not a Java developer, so I had limited knowledge of where to start troubleshooting.
I was troubleshooting with @anthonydahanne in a [Slack thread](https://paketobuildpacks.slack.com/archives/C0124SD3GTG/p1698258102926649) and …

Bump gradle wrapper networkTimeout to 10000 in sample

---

python/conda/environment.yml

This PR fixes this [issue](https://github.com/paketo-buildpacks/samples/issues/735) in the samples code
The issue seems to be import error. Flask cannot find the `Werkzeug` library
To fix it we need to add `Werkzeug` library 
More info: https://stackoverflow.com/questions/77213053/why-did-flask-start-failing-with-importerror-cannot-import-name-url-quote-fr
We will be able to execute the sample example code

Use Werkzeug 2.2.2 version inorder to work with Flask for samples code

---

nodejs/no-package-manager/server.js
nodejs/npm/server.js
nodejs/yarn/server.js

This PR adds the `/actuator/health` health check endpoint on the Node.js applications.
* This route is necessary in a Kubernetes environment to determine whether an application's status is healthy or not.
* This route exists on java applications, by adding them to the Node.js applications, we keep consistency across the samples.
This PR adds also a logging function for  the Node.js apps to log any incoming requests, which is helpful to know whether the request has been received by the server.

Node.js: Adding health check endpoints for a Kubernetes environment

---

.github/workflows/java-application-insights.yml
.github/workflows/java-aspectj.yml
.github/workflows/java-gradle.yml
.github/workflows/java-maven.yml
.github/workflows/java-opentelemetry.yml
.github/workflows/java-war.yml
.github/workflows/test-pull-request-java.yml

- Update Java versions tested with sample apps.
- Remove empty workflows that were causing errors
- Stop testing on base. This has never caught an error (i.e. something build on tiny, but not base) as far as I can remember, with the sample apps. We've also not got integration testing in the Java composite buildpack, so it's less important to test every combination of the samples.

Update Java versions tested & remove empty workflows

---

dotnet-core/aspnet/README.md
dotnet-core/aspnet/aspnet.csproj
dotnet-core/fdd-app/aspnet.deps.json
dotnet-core/fdd-app/aspnet.runtimeconfig.json
dotnet-core/fde-app/aspnet.deps.json
dotnet-core/fde-app/aspnet.runtimeconfig.json
dotnet-core/runtime/runtime.csproj

The dotnet-core/aspnet fails with recent Paketo Buildpacks Jammy Builder, due to
the fact that the version 6 runtime is no longer supported.

Bump target framework to `net8.0`

---

procfile/procfile-sample/Procfile
procfile/procfile-sample/main.go
procfile/procfile-sample/plan.toml
procfile/procfile_test.go

This PR removes the binary for amd64 for serving static files on procfile example and replaces it with a go program.
This will allow the app to be built for multiple architectures.

fix: replacing binary for amd64 with a go app
