paketo-buildpacks/samples

java/leiningen/README.md, java/leiningen/config/logback.xml, java/leiningen/project.clj, java/leiningen/src/lein_source/core.clj, java/leiningen/src/lein_source/server.clj, java/leiningen/src/lein_source/service.clj, java/leiningen/test/lein_source/core_test.clj, java/leiningen/test/lein_source/service_test.clj
Co-authored-by: Luis Alexander Aldazabal Gil <alexaldazabal@outlook.com>
=> Add leiningen sample

README.md, ruby/passenger/Gemfile, ruby/passenger/Passengerfile.json, ruby/passenger/README.md, ruby/passenger/app.rb, ruby/passenger/config.ru, ruby/passenger/views/index.erb, ruby/puma/Gemfile, ruby/puma/README.md, ruby/puma/app.rb, ruby/puma/config.ru, ruby/rackup/Gemfile, ruby/rackup/README.md, ruby/rackup/app.rb, ruby/rackup/config.ru, ruby/rake/Gemfile, ruby/rake/README.md, ruby/rake/Rakefile, ruby/thin/Gemfile, ruby/thin/README.md, ruby/thin/app.rb, ruby/thin/config.ru, ruby/unicorn/Gemfile, ruby/unicorn/README.md, ruby/unicorn/app.rb, ruby/unicorn/config.ru
cc @thitch97 
~- When a builder is available at `gcr.io/paketo-buildpacks/ruby`, the builder must be replaced with it.~
=> Add ruby sample apps

ca-certificates/README.md, ca-certificates/binding/type, ca-certificates/buildpack/bin/build, ca-certificates/buildpack/bin/detect, ca-certificates/buildpack/buildpack.toml, ca-certificates/go.mod, ca-certificates/main.go
Provide both build-time and runtime CA certificate examples.
=> Adds ca-certificates sample application

httpd/README.md, httpd/htdocs/index.html, httpd/httpd.conf, nginx/README.md
- Updates nginx image tag and docker run command in sample app README
Signed-off-by: Forest Eckhardt <feckhardt@pivotal.io>
Thanks for contributing. To speed up the process of reviewing your pull request
please provide us with:
* A short explanation of the proposed change:
Adds a top-level HTTPD sample application
* An explanation of the use cases your change enables:
Gives users a sample HTTPD app that is independent of PHP
Please confirm the following:
=> Adds httpd sample app

README.md, nodejs/no-package-manager/README.md, nodejs/no-package-manager/server.js, tests/node_test.go
- Adds sample app for support Nodejs workflow that does not use a
package manager
- Adds sample to tests
Resolves #11
=> Adds Nodejs sample app that does not use a package manager

README.md, php/composer/README.md, php/composer/composer.json, php/composer/composer.lock, php/composer/htdocs/.env, php/composer/htdocs/index.php, tests/php_test.go
Added sample for php composer
Fixes: #13
=> Added sample for php composer

java/leiningen/README.md
Fixes sample command to run leiningen sample.
Sample app fails with an OOME when using the previous command.
=> Bump up max metaspace for sample instructions, otherwise you'll end up with an OutOfMemoryError

java/dist-zip/gradle/wrapper/gradle-wrapper.properties, java/gradle/gradle/wrapper/gradle-wrapper.properties, java/kotlin/gradle/wrapper/gradle-wrapper.properties
This gradle upgrade should fix failing tests in 
#119 
#123
=> Upgrade gradle from 6.4 to 7.1

java/native-image/java-native-image-sample/pom.xml
Upgrades to Spring Boot 2.5.2 and Spring Native 0.10
=> Upgrade to Spring Boot 2.5.2 & Spring Native 0.10

java/native-image/java-native-image-sample/pom.xml
Updates to the latest version of Spring Boot.
Other sample apps seem to automatically bump Spring Boot versions, but not this native app. I haven't looked into why. This will bump it again. Maybe next time I'll see if I can figure out why the automation isn't updating it.
=> Updates Spring Boot to the latest version, 2.5.3

java/native-image/java-native-image-sample/pom.xml
Bumps Spring Boot & Native
To get latest versions.
=> Bump Spring Boot to 2.5.4 and Spring Native to 0.10.2

java/native-image/java-native-image-sample/pom.xml
Pull in the latest Spring Boot & Spring Native.
=> Bump Spring Boot to 2.5.5 and Spring Native to 0.10.3

nodejs/angular-npm/angular.json, nodejs/angular-npm/karma.conf.js, nodejs/angular-npm/package.json, nodejs/angular-npm/src/app/app.component.html, nodejs/angular-npm/src/app/app.component.spec.ts, nodejs/angular-npm/src/app/app.component.ts, nodejs/angular-npm/src/index.html, nodejs/angular-npm/src/polyfills.ts, nodejs/angular-npm/src/test.ts, nodejs/angular-npm/tsconfig.json, nodejs/angular-npm/tsconfig.spec.json
The app was throwing errors like the following on build:
```
npm ERR! Could not resolve dependency:
npm ERR! @angular/common@"~12.1.0-" from the root project
```
In this PR, I updated the angular depencencies by
updating ng-cli to the latest and recreating the app.
=> Update angular sample app

go/dep/buildpack.yml, go/dep/project.toml, nginx/nginx-sample/buildpack.yml
- Removes buildpack.yml in favor of project.toml with environment
variable in go/dep sample.
- Removes buildpack.yml in favor of default version behavior in nginx
sample.
=> Removes buildpack.yml files

.github/workflows/test-pull-request-dotnet-core.yml, .github/workflows/test-pull-request-go.yml, .github/workflows/test-pull-request-httpd.yml, .github/workflows/test-pull-request-java-native-image.yml, .github/workflows/test-pull-request-java.yml, .github/workflows/test-pull-request-nginx.yml, .github/workflows/test-pull-request-nodejs.yml, .github/workflows/test-pull-request-php.yml, .github/workflows/test-pull-request-procfile.yml, .github/workflows/test-pull-request-python.yml, .github/workflows/test-pull-request-ruby.yml, go.mod, go.sum, scripts/.util/test-workflow-template.yml
=> Removes go-version field in favor of using default for maintainablity

nodejs/npm/package.json
=> Update nodejs app

python/conda/environment.yml, python/pip/requirements.txt, python/pipenv/Pipfile, python/pipenv/Pipfile.lock
Bumps python dependencies to latest versions; removes unnecessary dependency definitions.
Supersedes #221 #222 #223
=> Update python dependencies.

git/git_test.go
=> Updates registry of git buildpack

python/poetry-run/README.md, python/poetry-run/default_app/server.py, python/poetry-run/default_app/templates/index.html, python/poetry-run/poetry.lock, python/poetry-run/pyproject.toml, python/poetry/Procfile, python/poetry/README.md, python/poetry/poetry.lock, python/poetry/pyproject.toml, python/poetry/server.py, python/poetry/templates/index.html, python/python_test.go
Adding sample applications for `poetry` - both as a package manager and also as a runnable executable.
=> Add poetry samples

nginx/nginx-sample/nginx.conf
=> Remove cloudfoundry reference

httpd/httpd_test.go, httpd/no-config-file-sample/README.md, httpd/no-config-file-sample/app/public/index.html, httpd/no-config-file-sample/binding/.htpasswd, httpd/no-config-file-sample/binding/type
=> Adds sample for zero config workflow in httpd

.github/workflows/test-all-samples.yml
Should fix build failures like [this one](https://github.com/paketo-buildpacks/samples/runs/6283669984?check_suite_focus=true).
Resolves #317
=> Add maven/gradle caching to Java test workflow

README.md
Add links to poetry samples in README.
=> Update README to include links to poetry samples.

web-servers/javascript-frontend-sample/README.md, web-servers/javascript-frontend-sample/httpd.toml, web-servers/javascript-frontend-sample/nginx.toml
=> Use web-servers language family buildpack in Javascript frontend sample

.github/workflows/test-pull-request-go.yml
The go buildpack is now included in the Jammy Tiny, Base and Full builders. We should test our samples against all of these.
=> Test Go Samples with Jammy

ruby/ruby_test.go
=> Fix ruby failures due to buildpack name changes

python/python_test.go
=> Fix python failures due to naming changes

nodejs/nodejs_test.go
=> Fix nodejs failures due to buildpack name changes

web-servers/web_servers_test.go
=> Fix web-server failures due to buildpack name changes

procfile/procfile_test.go
=> Fix procfile failure due to buildpack name changes

php/php_test.go
=> Fix php failures due to buildpack name changes

dotnet-core/dotnet_test.go
=> Fix dotnet-core failures due to buildpack name changes

java/java_test.go, java/native-image/java_native_image_test.go
=> Fix java failures due to buildpack name changes

java/java_test.go, java/native-image/java_native_image_test.go
https://github.com/paketo-buildpacks/samples/issues/387#issuecomment-1250555002
=> Fixes BellSoft buildpack name change

java/java_test.go
=> Update Java test assertions to reflect name change

java/java_test.go
=> update tomcat test assertion to reflect rename

dotnet-core/dotnet_test.go
Resolves .NET failures in #442
=> Update .NET Core log assertions to use new buildpack

web-servers/web_servers_test.go
so they don't fail before the container has started properly
Resolves #441 
Now, the web servers tests will wait for a container to come up and serve the proper response before failing out. This should help the tests pass more consistently.
=> Make web-servers tests less flaky

java/java_test.go
=> Updates the gid in the Java tests

java/native-image/java-native-image-sample/README.md, java/native-image/java-native-image-sample/pom.xml
* upgrade to Spring Boot 3.0.5
* clean up pom: configuration for native is included in the parent; including aot processing
=> Fix java native documentation

java/maven/README.md, java/native-image/java-native-image-sample/README.md, java/native-image/java-native-image-sample/pom.xml
* no need to use BP_NATIVE_IMAGE nor BP_MAVEN_BUILD_ARGUMENTS
=> Document with latest spring-boot and native buildpacks

java/native-image/java-native-image-sample/src/main/resources/application.properties
* so that GraalVM native build notices them and don't discard the code parsing those properties
=> Add default properties to management endpoint

java/native-image/quarkus-native/README.md, java/native-image/quarkus-native/pom.xml, java/native-image/quarkus-native/src/main/java/org/acme/getting/started/GreetingResource.java, java/native-image/quarkus-native/src/main/java/org/acme/getting/started/GreetingService.java, java/native-image/quarkus-native/src/test/java/org/acme/getting/started/NativeGreetingResourceIT.java
Updates Quarkus framework to the new major version 3
Fixes failing native-image w/ quarkus tests
=> Updates quarkus sample to Quarkus v3

java/gradle/smoke_test/gradle_test.go
=> Fix bug with duplicate env. variable assignment

ruby/puma/config.ru, ruby/thin/Gemfile
Update fixtures that were failing due to incompatibilities with Ruby 3.2
- thin: update the version in the Gemfile
- puma: remove the comment line in config.ru
https://github.com/paketo-buildpacks/builder-jammy-base/actions/runs/7743724339/job/21115782715?pr=425
=> Update Ruby fixtures

java/war/smoke_test/war_test.go
=> Force tomcat 10.1
